name: linux

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  c:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        curl:
          - '0'
          - '1'

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt install build-essential libcurl4-openssl-dev libx11-dev libxt-dev libimlib2-dev libxinerama-dev libjpeg-progs libtest-command-perl libtest-simple-perl libexif-dev
      - name: Build
        run: make
      - name: run Tests
        run: make test
